import os, io

class Gen():
    def __init__(self, path, version):
        self.path = path
        self.header = "###Generated by Wesnoth Addon Creator, version: "+version+"###\n"

    def unit(self, unit):
        with open(self.path+"/units/"+getattr(unit, "id")+".cfg", "w") as f:
            f.write(self.header)
            f.write("[unit_type]\n")
            atts = [["experience", 0], ["hitpoints", 0], ["id", 0], ["image", 1], ["movement", 0], ["name", 2]]
            for a in atts:
                self.writeAtt(f, unit, a[0], a[1])
            f.write("[/unit_type]\n")

    def writeAtt(self, file, obj, att, mode):
        """
        modes:
        0 - plain value
        1 - string
        2 - translatable string
        """
        if mode == 0:
            ln = "    "+att+" = "+getattr(obj, att)+"\n"
        elif mode == 1:
            ln = ("    "+att+" = \""+getattr(obj, att)+"\"\n")
        elif mode == 2:
            ln = ("    "+att+" = _ \""+getattr(obj, att)+"\"\n")
        file.write(ln)